// frontend/features/assessment/components/initial-form-data.ts

import type { AssessmentFormData } from './assessment.interface'

export const INITIAL_FORM_DATA: AssessmentFormData = {
  nome: '',
  nascimento: '',
  cpf: '',
  telefone: '',
  email: '',
  sexo: '',
  profissao: '',
  escolaridade: '',
  peso: '',
  altura: '',

  publico: '',
  queixaPrincipal: '',
  tempoSintomas: '',
  eventoDesencadeador: '',

  diagAnterior: '',
  diagAnterioresDetalhe: '',
  psicoterapia: '',
  internacao: '',
  condicoesCronicas: [],
  examesNeuro: '',
  examesNeuroDetalhe: '',

  triagemProfissional: '',
  triagemData: '',
  triagemFormato: '',
  transcricaoTriagem: '',
  triagemResumo: '',
  triagemObservacoes: '',

  sintomasAtuais: [],
  outrosSintomas: '',

  phq9: Array(9).fill(null) as null[],
  gad7: Array(7).fill(null) as null[],
  isi: Array(7).fill(null) as null[],
  asrs: Array(6).fill(null) as null[],
  aq10: Array(10).fill(null) as null[],
  ocir: Array(18).fill(null) as null[],
  mbi: Array(16).fill(null) as null[],
  pcl5: Array(8).fill(null) as null[],
  mdq: Array(13).fill(null) as null[],
  pss10: Array(10).fill(null) as null[],
  ad8: Array(8).fill(null) as null[],
  nms: Array(15).fill(null) as null[],
  alsfrs: Array(12).fill(null) as null[],
  snapiv: Array(18).fill(null) as null[],
  spin: Array(3).fill(null) as null[],
  auditc: Array(3).fill(null) as null[],

  mdqSimultaneo: '',
  mdqImpacto: '',

  usaMedicamento: '',
  medPassado: '',
  medPassadoDetalhe: '',
  efeitosAdversos: '',
  alergias: '',
  medicamentos: [],

  suplementos: [],
  supObs: '',

  uploads: {},

  possuiLaudos: '',
  laudosAnteriores: [],

  usaWearable: '',
  wDispositivo: '',
  wFCRepouso: '',
  wHRV: '',
  wSonoDuracao: '',
  wPassos: '',
  wEstresse: '',
  wearableObs: '',

  estadoCivil: '',
  satisfacaoRelacionamento: '',
  situacaoProfissional: '',
  cargaHoraria: '',
  horaDormir: '',
  horaAcordar: '',
  qualidadeSono: '',
  atividadeFisica: '',
  cafeina: '',
  tabaco: '',
  cannabis: '',
  neuromod: '',
  neuromodDetalhes: '',
  estresse: '',
  redeApoio: '',
  fontesEstresse: [],
  estiloVidaObs: '',

  familiaCondicoes: [],
  familiaDetalhes: '',
  infoAdicional: '',

  // B2B NR-1 fields
  srq20_answers: [],
  aep_answers: [],
  aep_percepcao_livre: '',
  canal_percepcao: null,
  b2b_anonymized_consent: false,
  b2c_consent: false,
  b2c_contact_consent: false,
}
