import {
  Autoformat,
  Bold,
  Italic,
  Underline,
  Essentials,
  Heading,
  HeadingButtonsUI,
  ParagraphButtonUI,
  Indent,
  Link,
  List,
  Paragraph,
  FontFamily,
  FontSize,
  FontColor,
  SourceEditing,
  TodoList,
  TodoListUI,
} from 'ckeditor5'
import type { Preset } from '@_sh/strapi-plugin-ckeditor'

import { STYLES, fontColor, fontFamily, fontSize } from '../configs'

const baseEditor: Preset = {
  name: 'baseEditor',
  description: 'Default Text Editor',
  styles: STYLES,
  editorConfig: {
    licenseKey: 'GPL',
    fontColor,
    fontFamily,
    fontSize,
    plugins: [
      Autoformat,
      Bold,
      Italic,
      Underline,
      Essentials,
      Heading,
      HeadingButtonsUI,
      ParagraphButtonUI,
      Indent,
      Link,
      List,
      Paragraph,
      FontFamily,
      FontSize,
      FontColor,
      SourceEditing,
      TodoList,
      TodoListUI,
    ],
    toolbar: [
      'paragraph',
      'heading1',
      'heading2',
      'heading3',
      'heading4',
      '|',
      'bold',
      'italic',
      'underline',
      '|',
      'fontColor',
      'FontFamily',
      'FontSize',
      '|',
      'link',
      '|',
      'bulletedList',
      'numberedList',
      'todoList',
      '|',
      'sourceEditing',
    ],
    heading: {
      options: [
        {
          model: 'paragraph',
          title: 'Paragraph',
          class: 'ck-heading_paragraph',
        },
        {
          model: 'heading2',
          view: 'h2',
          title: 'Heading 2',
          class: 'ck-heading_heading2',
        },
        {
          model: 'heading3',
          view: 'h3',
          title: 'Heading 3',
          class: 'ck-heading_heading3',
        },
        {
          model: 'heading4',
          view: 'h4',
          title: 'Heading 4',
          class: 'ck-heading_heading4',
        },
      ],
    },
  },
}

export default baseEditor
