// frontend/features/portal/constants/form-sections.ts

export const FORM_SECTIONS = [
  {
    id: 'personal',
    fields: [
      'nome',
      'nascimento',
      'cpf',
      'telefone',
      'email',
      'sexo',
      'profissao',
      'escolaridade',
      'peso',
      'altura',
    ],
  },
  {
    id: 'clinical',
    fields: ['publico', 'queixaPrincipal', 'tempoSintomas', 'eventoDesencadeador'],
  },
  {
    id: 'history',
    fields: [
      'diagAnterior',
      'diagAnterioresDetalhe',
      'psicoterapia',
      'internacao',
      'condicoesCronicas',
      'examesNeuro',
      'examesNeuroDetalhe',
    ],
  },
  {
    id: 'triage',
    fields: [
      'triagemProfissional',
      'triagemData',
      'triagemFormato',
      'transcricaoTriagem',
      'triagemResumo',
      'triagemObservacoes',
    ],
  },
  {
    id: 'symptoms',
    fields: ['sintomasAtuais', 'outrosSintomas'],
  },
  {
    id: 'scales',
    fields: [
      'phq9',
      'gad7',
      'isi',
      'asrs',
      'aq10',
      'ocir',
      'mbi',
      'pcl5',
      'mdq',
      'pss10',
      'ad8',
      'nms',
      'alsfrs',
      'snapiv',
      'spin',
      'auditc',
    ],
  },
  {
    id: 'medications',
    fields: [
      'usaMedicamento',
      'medicamentos',
      'medPassado',
      'medPassadoDetalhe',
      'efeitosAdversos',
      'alergias',
      'suplementos',
      'supObs',
    ],
  },
  {
    id: 'lifestyle',
    fields: [
      'estadoCivil',
      'satisfacaoRelacionamento',
      'situacaoProfissional',
      'cargaHoraria',
      'horaDormir',
      'horaAcordar',
      'qualidadeSono',
      'atividadeFisica',
      'cafeina',
      'tabaco',
      'cannabis',
      'neuromod',
      'neuromodDetalhes',
      'estresse',
      'redeApoio',
      'fontesEstresse',
      'estiloVidaObs',
    ],
  },
  {
    id: 'family',
    fields: ['familiaCondicoes', 'familiaDetalhes', 'infoAdicional'],
  },
  {
    id: 'wearables',
    fields: [
      'usaWearable',
      'wDispositivo',
      'wFCRepouso',
      'wHRV',
      'wSonoDuracao',
      'wPassos',
      'wEstresse',
      'wearableObs',
    ],
  },
] as const

export const FIELD_LABELS: Record<string, string> = {
  nome: 'Nome',
  nascimento: 'Data de nascimento',
  cpf: 'CPF',
  telefone: 'Telefone',
  email: 'E-mail',
  sexo: 'Sexo',
  profissao: 'Profissão',
  escolaridade: 'Escolaridade',
  peso: 'Peso',
  altura: 'Altura',
  publico: 'Perfil',
  queixaPrincipal: 'Queixa principal',
  tempoSintomas: 'Tempo de sintomas',
  eventoDesencadeador: 'Evento desencadeador',
  diagAnterior: 'Diagnóstico anterior',
  diagAnterioresDetalhe: 'Detalhes diagnósticos anteriores',
  psicoterapia: 'Psicoterapia',
  internacao: 'Internação',
  condicoesCronicas: 'Condições crônicas',
  examesNeuro: 'Exames neurológicos',
  examesNeuroDetalhe: 'Detalhes exames neurológicos',
  triagemProfissional: 'Profissional triagem',
  triagemData: 'Data triagem',
  triagemFormato: 'Formato triagem',
  transcricaoTriagem: 'Transcrição triagem',
  triagemResumo: 'Resumo triagem',
  triagemObservacoes: 'Observações triagem',
  sintomasAtuais: 'Sintomas atuais',
  outrosSintomas: 'Outros sintomas',
  phq9: 'PHQ-9',
  gad7: 'GAD-7',
  isi: 'ISI',
  asrs: 'ASRS',
  aq10: 'AQ-10',
  ocir: 'OCI-R',
  mbi: 'MBI',
  pcl5: 'PCL-5',
  mdq: 'MDQ',
  pss10: 'PSS-10',
  ad8: 'AD-8',
  nms: 'NMS-Quest',
  alsfrs: 'ALSFRS',
  snapiv: 'SNAP-IV',
  spin: 'SPIN',
  auditc: 'AUDIT-C',
  usaMedicamento: 'Usa medicamento',
  medicamentos: 'Medicamentos',
  medPassado: 'Medicação passada',
  medPassadoDetalhe: 'Detalhes medicação passada',
  efeitosAdversos: 'Efeitos adversos',
  alergias: 'Alergias',
  suplementos: 'Suplementos',
  supObs: 'Observações suplementos',
  estadoCivil: 'Estado civil',
  satisfacaoRelacionamento: 'Satisfação relacionamento',
  situacaoProfissional: 'Situação profissional',
  cargaHoraria: 'Carga horária',
  horaDormir: 'Hora dormir',
  horaAcordar: 'Hora acordar',
  qualidadeSono: 'Qualidade do sono',
  atividadeFisica: 'Atividade física',
  cafeina: 'Cafeína',
  tabaco: 'Tabaco',
  cannabis: 'Cannabis',
  neuromod: 'Neuromodulação',
  neuromodDetalhes: 'Detalhes neuromodulação',
  estresse: 'Estresse',
  redeApoio: 'Rede de apoio',
  fontesEstresse: 'Fontes de estresse',
  estiloVidaObs: 'Observações estilo de vida',
  familiaCondicoes: 'Condições familiares',
  familiaDetalhes: 'Detalhes familiares',
  infoAdicional: 'Informações adicionais',
  usaWearable: 'Usa wearable',
  wDispositivo: 'Dispositivo',
  wFCRepouso: 'FC repouso',
  wHRV: 'HRV',
  wSonoDuracao: 'Duração do sono',
  wPassos: 'Passos',
  wEstresse: 'Estresse',
  wearableObs: 'Observações wearable',
}
